### ISSUE TITLE
Add Instructions for Adding Collaborators in Workflow Page

### ISSUE THREAD

**Issue by Josh-McMillan** [Josh-McMillan/Community-Game#7]
It seems that not everyone has access to fork or clone the repo, so it's probably a good idea in the Workflow wiki page to add that people need to be added as collaborators before they can get started working.

The process for that is as outlined:
- Message me (SpatialPlays) on Discord with either your email or your GitHub username
- I'll add you to the collaborators list as soon as I have an opportunity
- After you're added, you may continue as outlined in the Workflow documentation

**Comment by AlexanderKyron** [comment]
Added to the workflow guide; please confirm that this is acceptable: https://github.com/Josh-McMillan/Community-Game/wiki/Workflow

**Comment by Josh-McMillan** [comment]
Yes, looks acceptable. You might want to make a heading or notice statement so that people don't overlook it in the sea of text, but otherwise looks good. Only one question: Are the instructions after the notice counting up from 0?

**Comment by AlexanderKyron** [comment]
Fixed the counting from zero and added a bold "Notice".
